### ISSUE TITLE
Opentrons import on install

### ISSUE THREAD

**Issue by marcosfelt** [PyLabRobot/pylabrobot#3]
Thanks for creating this! I was trying to run the [simulator example](https://docs.pylabrobot.org/using-the-simulator.html), and got this error:

```bash
WARNING:pylabrobot.liquid_handling.backends.hamilton.STAR:Could not import pyusb, Hamilton interface will not be available.
Traceback (most recent call last):
  File "simulate.py", line 1, in <module>
    from pylabrobot.liquid_handling import LiquidHandler
  File "/Users/Kobi/Documents/Research/phd_code/other/pylabrobot/.venv/lib/python3.8/site-packages/pylabrobot/liquid_handling/__init__.py", line 3, in <module>
    from .backends import LiquidHandlerBackend, STAR
  File "/Users/Kobi/Documents/Research/phd_code/other/pylabrobot/.venv/lib/python3.8/site-packages/pylabrobot/liquid_handling/backends/__init__.py", line 8, in <module>
    from .opentrons_backend import OpentronsBackend
  File "/Users/Kobi/Documents/Research/phd_code/other/pylabrobot/.venv/lib/python3.8/site-packages/pylabrobot/liquid_handling/backends/opentrons_backend.py", line 12, in <module>
    from pylabrobot.liquid_handling.resources.opentrons import OTDeck
  File "/Users/Kobi/Documents/Research/phd_code/other/pylabrobot/.venv/lib/python3.8/site-packages/pylabrobot/liquid_handling/resources/opentrons/__init__.py", line 2, in <module>
    from .load import load_opentrons_resource, load_shared_opentrons_resource
  File "/Users/Kobi/Documents/Research/phd_code/other/pylabrobot/.venv/lib/python3.8/site-packages/pylabrobot/liquid_handling/resources/opentrons/load.py", line 5, in <module>
    import opentrons_shared_data
ModuleNotFoundError: No module named 'opentrons_shared_data'
```

Any ideas?

**Comment by rickwierenga** [comment]
This is an old error, that has since been fixed (in https://github.com/PyLabRobot/pylabrobot/commit/08445845fe57e7ca81790e35031714c4b1e11be9).

I just published the current library on PyPI, so if you installed using `pip` just run `pip install --upgrade pylabrobot`.
If you installed from source, run `git pull`.
